### ISSUE TITLE
Timestamp are displayed to locale timezone instead of conference timezone

### ISSUE THREAD

**Issue by oldergod** [paug/AndroidMakersApp#110]
I don't think any event are gonna be broadcasted live online so I think it'd make sense to display times to Paris's timezone instead of using the locale one.
Not really important but a bit confusing when one wanna organize their day while still overseas.

![image](https://user-images.githubusercontent.com/1767669/164537505-033e8264-9fa3-4a54-a472-3236b35db951.png)

**Comment by martinbonnin** [comment]
Dammit! Time is hard!

**Comment by martinbonnin** [comment]
But thanks for the bug report :) I'll look into it, final call for the final version is soon-ish.

**Comment by martinbonnin** [comment]
PR there: https://github.com/paug/AndroidMakersApp/pull/112
