### ISSUE TITLE
filter not working as expected

### ISSUE THREAD

**Issue by underwindfall** [paug/AndroidMakersApp#116]
Hello,
Currently, when I use this app to apply filters to events, I realised it's been filtered by `Or` logic. The specific use case is 
when the user chooses `Language English + Rooms Moebius`, the app will display all events which supported `Language English or Rooms Moebius`.  

What I expected is the events will be filtered by `Language English + Rooms Moebius`.

And if the user continues to choose more rooms, the events will be filtered like `Language English + (Rooms Moebius or Rooms A...)`.

I wonder whether it's something we want or not?  If it's not, could I make a PR for this since I have an idea to how to deal with this issue?

|   current	|   expected	| 
| -- | -- |
|   <img width="461" alt="image" src="https://user-images.githubusercontent.com/14819756/164723577-9c8dc395-3331-4f38-913c-ef2d99c7d23e.png"/>	 |   <img width="448" alt="image" src="https://user-images.githubusercontent.com/14819756/164723918-6452fef0-349c-4d32-acb4-61c177b60a00.png"/>|

**Comment by martinbonnin** [comment]
That makes perfect sense. A PR is very welcome, I can do a new release tonight or tomorrow. 

I still think inside a same category, it should be an "or" obviously or else the result will be empty`(Moebius || Blin) && English` (and not `Moebius && Blin && English`)

**Comment by underwindfall** [comment]
> That makes perfect sense. A PR is very welcome, I can do a new release tonight or tomorrow.
> 
> ~I still think inside a same category, it should be an "or" obviously or else the result will be empty`(Moebius || Blin) && English` (and not `Moebius && Blin && English`)~ Edit: never mind, this is just what you said 👍

great ! 👍  PR has been made. https://github.com/paug/AndroidMakersApp/pull/118
