### ISSUE TITLE
Language Filter not working

### ISSUE THREAD

**Issue by anandwana001** [paug/AndroidMakersApp#135]
The Language field is coming null from backend due to which the Language Filter is not working.

<img width="505" alt="Screenshot 2023-04-10 at 21 43 19" src="https://user-images.githubusercontent.com/25057618/230943669-1ac43120-6c8b-493d-8d93-94fcf9da26d0.png">

**Comment by martinbonnin** [comment]
Good catch 👍 

I haven't found that data in the [sessionize JSON](https://sessionize.com/api/v2/72i2tw4v/view/All) but we can add it manually [there](https://github.com/paug/AndroidMakersBackend/blob/main/backend/service-graphql/src/main/resources/data.json) + most likely modifying the schema a bit. Feel free to open a PR or I'll look into it a bit later this week

**Comment by anandwana001** [comment]
Open a PR at backend repo - https://github.com/paug/AndroidMakersBackend/pull/4

**Comment by martinbonnin** [comment]
This should be good now. Please leave a message if this is still happening.
