### ISSUE TITLE
Agenda List: Clickable and non-clicakable sessions have the same visual

### ISSUE THREAD

**Issue by Smoochibi** [paug/AndroidMakersApp#157]
Clickable and non-clicakable sessions have the same visual which makes the behaviour confusing to grasp.
It also makes the behavior on non-clickable sessions look like a bug.

**Comment by martinbonnin** [comment]
Any preference how we should hint users about this?

**Comment by martinbonnin** [comment]
Made a try there: https://github.com/paug/AndroidMakersApp/pull/164
