### ISSUE TITLE
Agenda List: The touch target on the Bookmark Button is too small

### ISSUE THREAD

**Issue by Smoochibi** [paug/AndroidMakersApp#158]
On the Agenda List, the touch target on the Bookmark Button is too small which makes it hard to use because the user might be sent to the Session Details by clicking outside the target by mistake.

This might also be considered an accessibility issue.

Of course, this issue is only present on the sessions that have details.

**Comment by martinbonnin** [comment]
Made a try there: https://github.com/paug/AndroidMakersApp/pull/164
