### ISSUE TITLE
Session Details: The font size applied on the Information Block under the Title is too small (Accessibility)

### ISSUE THREAD

**Issue by Smoochibi** [paug/AndroidMakersApp#159]
In the Session Details, the font size applied on the Information Block under the Title is too small.
It's already hard to read for someone with a good eyesight so it's probably an accessibility issue.

**Comment by mdupierreux** [comment]
![Screenshot_20230424_161044](https://user-images.githubusercontent.com/526001/234022441-b2900faf-687d-42ae-983a-9037247d48f4.png)

Maybe something like this would be better (inspired from Confetti 😄 )

**Comment by martinbonnin** [comment]
Tentative fix [here](https://github.com/paug/AndroidMakersApp/pull/163), let me know what you think
