### ISSUE TITLE
Add a link to submit an app to the App Clinic Session

### ISSUE THREAD

**Issue by g123k** [paug/AndroidMakersApp#208]
Hi everyone,

There will be, once again, an App Clinic session this year, and it would be very nice to add a link to the submission form.
It could be a link in the session… or even better, a link in a menu or something like that

**Comment by enthuan** [comment]
Which kind of form is it? Do you have a link please?

**Comment by RobinCaroff** [comment]
I'll have a look at it today. I'll keep you psted.
