### ISSUE TITLE
Make sure we can update the floor plan last minute if needed

### ISSUE THREAD

**Issue by martinbonnin** [paug/AndroidMakersApp#221]
We have a new room this year (Dev Lounge), we'll want to update the PNG

**Comment by enthuan** [comment]
The image is in a shared / ui folder : 
```
shared/ui/src/commonMain/moko-resources/images/beffroi@1x.png
```

Do you have the original PNG source for modifying if needed?

**Comment by martinbonnin** [comment]
Sorry I should have left a better message I was talking with Jana at droidcon and they have a designer working on an updated floor plan. They'll share it but it probably won't be ready for the first submission (probably next week?). 

This issue is about using a url instead of a hardcoded png so that we can update the floor plan as needed.
