### ISSUE TITLE
Idea : reduce the size of the header

### ISSUE THREAD

**Issue by enthuan** [paug/AndroidMakersApp#224]
With the AM logo + the title + the tabbar, the size of the agenda is a bit small. 
Analyze a small top bar solution or try to collapse it when scrolling.

**Comment by enthuan** [comment]
https://github.com/paug/AndroidMakersApp/assets/8111500/1e095843-8adf-4013-b1a8-8fa655266661

@benju69 @martinbonnin 
Is this behavior ok?

**Comment by enthuan** [comment]
It is on iPhone SE which is, TMO, one of the smallest phones in 2024 😄

**Comment by benju69** [comment]
looks good :)

**Comment by martinbonnin** [comment]
Much better, thanks!
