### ISSUE TITLE
Rename repo

### ISSUE THREAD

**Issue by benju69** [paug/AndroidMakersApp#24]
and module app, and improve Readme

**Comment by LouisCAD** [comment]
@benju69 Rename module app... to what?

**Comment by benju69** [comment]
AndroidMakersApp (ou un truc du genre) ça serait mieux après pas obligé
Et le nom du repo sans le 2017

**Comment by LouisCAD** [comment]
I think renaming the repo is the first step, because the longer you wait, the more the future broken links spread, and it's also the simplest step. Why not do it now?

**Comment by LouisCAD** [comment]
AndroidMakersApp would be a good name for this repo IMHO.
