### ISSUE TITLE
Line breaks not supported in session description

### ISSUE THREAD

**Issue by RobinCaroff** [paug/AndroidMakersApp#253]
Line breaks not supported in session description.

This is particularly visible with Devlicious or App-Clinic sessions descriptions but also happens with other sessions.

This is due to the `removeHtmlTags' instruction :
https://github.com/paug/AndroidMakersApp/blob/8917af5b7a458f478b2a915e744479e59d6a5127/shared/ui/src/commonMain/kotlin/com/androidmakers/ui/agenda/SessionDetailLayout.kt#L223

Here are web vs Android apps screenshot comparisons :

![Artboard1](https://github.com/paug/AndroidMakersApp/assets/10415655/7e654b08-28eb-4ea8-9c5f-822d73803757)

![Artboard1_2](https://github.com/paug/AndroidMakersApp/assets/10415655/941925b2-84ad-45c4-8397-544cba1bc325)

## Environment

Happens with the Android app
Looks fine on iOS.

## Steps to reproduce

Opens the App-Clinic session details.

**Comment by BoD** [comment]
I don't know why 😅 but FWIW it looks like the problem's not there on WearOS 

![Screenshot_1712757240](https://github.com/paug/AndroidMakersApp/assets/372852/7ac5845a-e4fd-4d81-a096-f57daae4bfc5)

**Comment by RobinCaroff** [comment]
I have a dirty fix :

```
text = sessionDetails.session.description?.replace("\n", "<br />")?.removeHtmlTags() ?: "",
```

but I wonder if it would not be better to do it in the Sessionize data import script on the server side. Ping @martinbonnin @BoD

**Comment by martinbonnin** [comment]
If I understand correctly, format choices for `Session.description` are:

* Markdown
* JSON encoded string (current)
* HTML

Am I correct?

I think I prefer the current state where the backend data is transfered using a JSON encoded (hence containing `\n`). I prefer that over HTML that is generally wayyyyyyy more complicated to handle. Markdown could be nice too but if WearOS and iOS are OK already, replacing the `/n` -> `<br/>` is probably the path of least resistance?

**Comment by RobinCaroff** [comment]
OK I'll make a fix.
