### ISSUE TITLE
Agenda : problèmes de marges (sur le bas)

### ISSUE THREAD

**Issue by g123k** [paug/AndroidMakersApp#4]
![screenshot_20170327-101645](https://cloud.githubusercontent.com/assets/246838/24347007/21d13226-12d7-11e7-9958-5b64c7f752c7.png)

Il manque les marges sur le bas des événements.

**Comment by StanKocken** [comment]
Ouais, mais avec les marges c'est pire, car ça coupe le texte. Je n'ai pas trouvé de solution où juste "Seriously" n'est pas affiché

**Comment by n0tnull** [comment]
@StanKocken Et si on utilisait une TextView avec taille de texte dynamique ?

**Comment by StanKocken** [comment]
Pour avoir un texte tout petit car c'est un long titre dans une session de
20min ? Non je ne suis pas fan

**Comment by n0tnull** [comment]
L'affichage de l'agenda n'utilisant plus ce composant, ce problème peut être fermé.
