### ISSUE TITLE
Agenda : ajouter ellipsize sur les boutons

### ISSUE THREAD

**Issue by g123k** [paug/AndroidMakersApp#5]
![screenshot_20170327-102216](https://cloud.githubusercontent.com/assets/246838/24347096/7ce6191a-12d7-11e7-9601-492680fb39f3.png)

Il faudrait ajouter un ellipsize sur les boutons lorsque le texte est trop long

**Comment by StanKocken** [comment]
Les ellipsizes et les multi-lines… C'est toujours compliqué. Tu as une solution ?

**Comment by benju69** [comment]
En effet chaud en multi lines :/ à moins de séparer le texte en petites parties (et après TextUtils.ellipsize() : http://stackoverflow.com/questions/4012232/draw-text-ellipsized-to-a-canvas )

**Comment by n0tnull** [comment]
L'affichage de l'agenda n'utilisant plus ce composant, ce problème peut être fermé.
