### ISSUE TITLE
Can't see all partners in the about page

### ISSUE THREAD

**Issue by GerardPaligot** [paug/AndroidMakersApp#99]
Bug description: When I open the AM 2022 app and go to the about page, there are some white space clickable which correspond to some partners (e.g. Babbel).
Phone: One Plus 7T
OS version: Android 11 (Oxygen OS 11.0.6.1)
App version: 1.4.2

![image](https://user-images.githubusercontent.com/1913901/164156824-25dda611-de98-4aa3-acf5-08ad2c1aeb5b.png)

**Comment by martinbonnin** [comment]
Thanks ! These are the jpeg logos which somehow need some special handling. Fix is [there](https://github.com/paug/AndroidMakersApp/pull/94/commits/2a289fc25e2cfddf6aad9fdb7367f4f1809f4da5). It'll be included in the next version
